title: A Robot's Gradient Ascent 
description: Daniele Moro's Blog

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Author's home: "http://danielemoro.com"

avatar: "google_portrait.jpg"

author:
  name: Some Person
  
social-network-links:
  rss: true
  email: "moro.daniele@gmail.com"
  linkedin: https://www.linkedin.com/in/daniele-moro
  github: https://github.com/danielemoro
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

theme: jekyll-theme-slate
